#!/usr/bin/env python
##### Ninn Command Line Tool #####
# Author : Alexandre Ravaux 
# @date:2016/02/20
# @python:/usr/bin/env python
import sys
print "You've called the Ninn Command Line Tools"
print 'Number of arguments:', len(sys.argv), 'arguments.'
print 'Argument List:', str(sys.argv)
if len(sys.argv) > 2:
	print "Yay"
else:
	print "Nein, nein, nein ! Nicht gut !"